# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
# heavily inspired from https://github.com/wiverson/maven-jpackage-template/blob/main/.github/workflows/maven-build-installer-windows.yml

name: Java CI with Maven

on:
  push:
    branches: [ reloaded ]
  pull_request:
    branches: [ reloaded ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Wix
      uses: i3h/download-release-asset@v1
      with:
        owner: wixtoolset
        repo: wix3
        tag: wix3112rtm
        file: wix311-binaries.zip
    - name: Decompress Wix
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: wix311-binaries.zip
        pathTarget: ./target/wix
    - name: Add Wix to Path
      run: echo "$HOME/target/wix" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create windows executable
      run: jpackage --type exe --name arx --input D:\a\ARX\ARX\target\assembly --main-jar arx.jar --main-class cz.kojotak.arx.DesktopRunner --win-console --dest D:\a\ARX\ARX\target\assembly --win-dir-chooser --add-modules java.base,java.desktop,java.prefs,java.sql
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: D:\a\ARX\ARX\target\assembly\*.exe
